export { default as App } from './App';
export { default as Title } from './Title';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Activities } from './Activities';
export { default as Routines } from './Routines';
export { default as GetSingleRoutine } from './GetSingleRoutine';
export { default as SingleRoutineView } from './SingleRoutineView';
export { default as GetSingleActivity } from './GetSingleActivity';
export { default as SingleActivityView } from './SingleActivityView';
export { default as CreateActivity } from './CreateActivity';
export { default as CreateRoutine } from './CreateRoutine';
export { default as MyRoutines } from './MyRoutines';
export { default as UpdateRoutine } from './UpdateRoutine';
export { default as UpdateActivity} from './UpdateActivity';
//export {default as UpdateRoutineActivity} from './UpdateRoutineActivity';
//export { default as DeleteRoutineActivity } from './DeleteRoutineActivity;
export { default as APIURL } from './APIURL';